// GENERATED by scripts/generate-coderabbit-checks.mjs from plugins/api-compatibility/skills/mobile-api-compatibility.
// Do not edit by hand; change the skill and re-run the script.
import type { CodeRabbitConfig } from "@coderabbitai/config"

export default {
	reviews: {
		pre_merge_checks: {
			custom_checks: [
				{
					mode: "error",
					name: "Mobile API Compatibility Guidelines",
					instructions: `Evaluate the change against the mobile-api-compatibility skill from sharechat-ai-context.
The full text of the skill is included below; it is the complete set of rules for this check.

- Fail if the change violates any rule below. For each violation, quote the rule, name the file it
  comes from (as labelled below), and point to the line in this PR that violates it.
- Consider the effect of the change, not only the lines edited: a dependency, configuration, or library
  change can violate a rule about API responses without touching the API code itself.
- In the result, list which skill files were applied.
- Pass if no rule is violated.

===== plugins/api-compatibility/skills/mobile-api-compatibility/SKILL.md =====
# Mobile API compatibility

Old app versions stay installed for months. An API change ships to every user at once, while a
client change reaches users slowly, one app update at a time. So **every API change must keep working for
clients built before it.**

## Find the contract

Each service owns its contract and keeps it next to its code, usually at \`api/openapi.yaml\`.
The repo's \`.coderabbit.yaml\` or README names the contract path and the client repos that consume it.
Never copy a contract into another repo. Read it from the service that owns it.

## When changing an API (backend service)

1. Read the contract before touching any handler, model, or serializer it covers.
2. Classify the change with \`references/compatibility-rules.md\`:
   - **Additive** (new optional field, new optional query param): allowed in the current version.
   - **Breaking** (remove, rename, or retype a field; make a field required or nullable; change enum
     meaning or pagination): not allowed in the current version. Add a new version (e.g. \`/v2\`) and keep the old one serving.
3. Update the contract in the same PR as the code.
4. Give new fields a default value.
5. Deprecate before removing: mark the field \`deprecated: true\`, keep serving it for at least 2 app release
   cycles, and remove it only when the minimum supported app versions no longer read it.

## When consuming an API (Android / iOS app)

1. Parse leniently: ignore unknown fields, and map unknown enum values to an \`unknown\` case
   instead of crashing.
2. Never assume an optional field is present. Fall back to a safe default.
3. Treat pagination cursors and IDs as opaque strings.
4. Before reading a new field, check that it is in the service's contract and already served in production.

## Review checklist

- [ ] Contract updated in the same PR as the code
- [ ] No field removed, renamed, or retyped in an existing version
- [ ] No optional field made required or nullable
- [ ] New enum values are safe for old clients (they map to \`unknown\`)
- [ ] Pagination and error response shapes are unchanged
- [ ] Every consuming client repo checked if the response shape changed

===== plugins/api-compatibility/skills/mobile-api-compatibility/references/compatibility-rules.md =====
# API compatibility rules

| Change | Breaking? | What to do |
|---|---|---|
| Add an optional response field | No | Ship in the current version with a default |
| Add an optional query parameter | No | Ship in the current version; keep the old behaviour when it's absent |
| Add an enum value | Risky | OK only if clients map unknown values to \`unknown\` |
| Remove a response field | **Yes** | Deprecate first; remove only after 2 release cycles |
| Rename a field (e.g. \`handle\` → \`username\`) | **Yes** | Add the new field next to the old one, then deprecate the old one |
| Change a field's type (e.g. string ID → int) | **Yes** | New version (\`/v2\`) |
| Make an optional field required, or a non-null field nullable | **Yes** | New version |
| Change pagination defaults, limits, or cursor semantics | **Yes** | New version |
| Change the error response shape | **Yes** | New version |
| Change which results are returned or their order | No (contract) | Behaviour change: note it in the PR, no version bump |`,
				},
			],
		},
	},
} satisfies CodeRabbitConfig
